name: Run Tests with Bun

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Bun
      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "export BUN_INSTALL=\"$HOME/.bun\"" >> $GITHUB_ENV
          echo "export PATH=\"$HOME/.bun/bin:$PATH\"" >> $GITHUB_ENV

      # Install project dependencies (if any)
      - name: Install dependencies
        run: bun install

      # Run the tests using Bun
      - name: Run Tests
        run: bun run test
